@testable import hunch
import XCTest

final class VTTTranscriptTests: XCTestCase {

    // MARK: - A real file

    /// The fixture is the opening of a real yt-dlp pull, kept verbatim rather than hand-written,
    /// because every quirk exercised below is one this parser met on disk and not one it was
    /// designed against: the padding line, the ten-millisecond hold cues, the scrolling window, the
    /// per-word timing tags, and a file that simply stops mid-cue.
    func testParsingARealAutoGeneratedFileKeepsEachLineOnceInOrder() throws {
        let parsed = VTTTranscript.parse(try fixture(named: "auto-generated"))

        XCTAssertEqual(parsed, [
            TranscriptLine(start: 0.320, text: "I mean, like, if I'm facing forward, my"),
            TranscriptLine(start: 2.879, text: "right foot is to my right, like"),
            TranscriptLine(start: 6.240, text: "directly. So, basically, you're you're"),
            TranscriptLine(start: 8.160, text: "you're trying to twist your heel. Yeah."),
            TranscriptLine(start: 10.559, text: "Your toes out. So, your heels are like"),
            TranscriptLine(start: 13.040, text: "almost parallel like like you can't see"),
            TranscriptLine(start: 15.360, text: "it on my stream like, \"Oh, yeah. I could")
        ])
    }

    /// The first thing said in an auto-generated file sits under a line holding a single space. Read
    /// that as the blank line that ends a cue and the opening line of every video goes missing, so
    /// it is worth pinning separately from the whole-file comparison above.
    func testTheFirstSpokenLineSurvivesThePaddingLineAboveIt() throws {
        let parsed = VTTTranscript.parse(try fixture(named: "auto-generated"))

        XCTAssertEqual(parsed.first?.text, "I mean, like, if I'm facing forward, my")
    }

    /// yt-dlp writes as much as it read, so its files routinely stop after a payload line with no
    /// blank line under it. Only closing the open cue at EOF renders that last line.
    func testTheFinalCueIsRenderedWithoutATrailingBlankLine() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            the last thing said
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 1, text: "the last thing said")])
    }

    // MARK: - Timings

    func testHoursMayBeLeftOffTheTimestamp() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            01:05.500 --> 01:07.000
            partway in
            """)

        XCTAssertEqual(parsed.first?.start, 65.5)
    }

    func testTheSettingsAfterATimestampAreIgnored() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:01:02.500 --> 00:01:04.000 align:start position:0% line:90%
            words
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 62.5, text: "words")])
    }

    /// WebVTT writes milliseconds after a dot, but files that have been through a converter carry
    /// the comma SRT uses, and reading it as an unparseable number would drop the cue entirely.
    func testMillisecondsMayBeSeparatedByAComma() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01,250 --> 00:00:02,000
            words
            """)

        XCTAssertEqual(parsed.first?.start, 1.25)
    }

    /// A cue whose timing cannot be read has nowhere to be rendered, so it is dropped rather than
    /// guessed at - and dropping it must not take the rest of the file with it.
    func testACueWithAnUnreadableTimingLineIsDroppedOnItsOwn() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            whenever --> later
            dropped

            00:00:05.000 --> 00:00:06.000
            kept
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 5, text: "kept")])
    }

    // MARK: - Cue text

    func testMarkupIsStrippedFromTheText() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            <v Speaker>the <i>emphasised</i> word<00:00:02.000><c> after</c>
            """)

        XCTAssertEqual(parsed.first?.text, "the emphasised word after")
    }

    /// Escapes are decoded after the markup strip, so a bracket someone wrote as text is never read
    /// as the start of a tag that swallows the rest of the line.
    func testEscapesAreDecodedAfterMarkupIsStripped() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            5 &lt; 6 &amp;&amp; 7 &gt; 6 &quot;yes&quot; it&#39;s
            """)

        XCTAssertEqual(parsed.first?.text, "5 < 6 && 7 > 6 \"yes\" it's")
    }

    /// The ampersand is decoded last for this: someone writing about an escape gets the escape back
    /// rather than the character it names.
    func testAnEscapedEscapeIsDecodedOnlyOnce() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            write &amp;lt; for a bracket
            """)

        XCTAssertEqual(parsed.first?.text, "write &lt; for a bracket")
    }

    // MARK: - Everything that is not cue text

    func testCueIdentifiersAreNotTranscript() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            opening
            00:00:01.000 --> 00:00:02.000
            first

            closing
            00:00:03.000 --> 00:00:04.000
            second
            """)

        XCTAssertEqual(parsed, [
            TranscriptLine(start: 1, text: "first"),
            TranscriptLine(start: 3, text: "second")
        ])
    }

    func testNoteBlocksAreNotTranscript() {
        let parsed = VTTTranscript.parse("""
            WEBVTT
            Kind: captions
            Language: en

            NOTE
            this file was generated by a robot

            00:00:01.000 --> 00:00:02.000
            words
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 1, text: "words")])
    }

    func testWindowsLineEndingsParse() {
        let contents = "WEBVTT\r\n\r\n00:00:01.000 --> 00:00:02.000\r\nwords\r\n"

        XCTAssertEqual(VTTTranscript.parse(contents), [TranscriptLine(start: 1, text: "words")])
    }

    // MARK: - Repetition

    /// Two lines is the window YouTube scrolls today, so the overlap is measured rather than assumed
    /// to be one line - a three line window would otherwise render every line twice.
    func testAWindowTallerThanTwoLinesStillDeduplicates() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            one
            two
            three

            00:00:02.000 --> 00:00:03.000
            two
            three
            four
            """)

        XCTAssertEqual(parsed, [
            TranscriptLine(start: 1, text: "one two three"),
            TranscriptLine(start: 2, text: "four")
        ])
    }

    /// Only the scrolling window is collapsed, not the video's vocabulary. Someone who says the same
    /// word twice a minute apart said it twice.
    func testALineThatRecursLaterIsRenderedAgain() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            yeah

            00:00:02.000 --> 00:00:03.000
            yeah

            00:00:03.000 --> 00:00:04.000
            totally

            00:00:04.000 --> 00:00:05.000
            yeah
            """)

        XCTAssertEqual(parsed, [
            TranscriptLine(start: 1, text: "yeah"),
            TranscriptLine(start: 3, text: "totally"),
            TranscriptLine(start: 4, text: "yeah")
        ])
    }

    // MARK: - Reading from disk

    func testLoadingAFileThatIsNotThereIsNil() {
        let missing = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathComponent("transcript.vtt")

        XCTAssertNil(VTTTranscript.load(from: missing))
    }

    /// The two answers a caller has to tell apart: yt-dlp never wrote a file here, versus yt-dlp
    /// wrote one and there was nothing in it. Only the first is nil.
    func testLoadingAFileWithNoCuesIsEmptyRatherThanNil() throws {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("\(UUID().uuidString).vtt")
        try "WEBVTT\nKind: captions\nLanguage: en\n".write(to: url, atomically: true, encoding: .utf8)
        defer { try? FileManager.default.removeItem(at: url) }

        XCTAssertEqual(VTTTranscript.load(from: url), [])
    }

    // MARK: - Helpers

    private func fixture(named name: String) throws -> String {
        let url = try XCTUnwrap(Bundle.module.url(forResource: name, withExtension: "vtt", subdirectory: "Fixtures"),
                                "missing fixture \(name).vtt")
        return try String(contentsOf: url, encoding: .utf8)
    }
}
