@testable import hunch
import XCTest

final class VTTTranscriptTests: XCTestCase {

    // MARK: - A real file

    /// The fixture is the opening of a real yt-dlp pull, kept verbatim rather than hand-written,
    /// because every quirk exercised below is one this parser met on disk and not one it was
    /// designed against: the padding line, the ten-millisecond hold cues, the scrolling window, the
    /// per-word timing tags, and a file that simply stops mid-cue.
    func testParsingARealAutoGeneratedFileKeepsEachLineOnceInOrder() throws {
        let parsed = VTTTranscript.parse(try fixture(named: "auto-generated"))

        XCTAssertEqual(parsed, [
            TranscriptLine(start: 0.320, text: "I mean, like, if I'm facing forward, my"),
            TranscriptLine(start: 2.879, text: "right foot is to my right, like"),
            TranscriptLine(start: 6.240, text: "directly. So, basically, you're you're"),
            TranscriptLine(start: 8.160, text: "you're trying to twist your heel. Yeah."),
            TranscriptLine(start: 10.559, text: "Your toes out. So, your heels are like"),
            TranscriptLine(start: 13.040, text: "almost parallel like like you can't see"),
            TranscriptLine(start: 15.360, text: "it on my stream like, \"Oh, yeah. I could")
        ])
    }

    /// The first thing said in an auto-generated file sits under a line holding a single space. Read
    /// that as the blank line that ends a cue and the opening line of every video goes missing, so
    /// it is worth pinning separately from the whole-file comparison above.
    func testTheFirstSpokenLineSurvivesThePaddingLineAboveIt() throws {
        let parsed = VTTTranscript.parse(try fixture(named: "auto-generated"))

        XCTAssertEqual(parsed.first?.text, "I mean, like, if I'm facing forward, my")
    }

    /// yt-dlp writes as much as it read, so its files routinely stop after a payload line with no
    /// blank line under it. Only closing the open cue at EOF renders that last line.
    func testTheFinalCueIsRenderedWithoutATrailingBlankLine() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            the last thing said
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 1, text: "the last thing said")])
    }

    // MARK: - Timings

    func testHoursMayBeLeftOffTheTimestamp() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            01:05.500 --> 01:07.000
            partway in
            """)

        XCTAssertEqual(parsed.first?.start, 65.5)
    }

    func testTheSettingsAfterATimestampAreIgnored() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:01:02.500 --> 00:01:04.000 align:start position:0% line:90%
            words
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 62.5, text: "words")])
    }

    /// WebVTT writes milliseconds after a dot, but files that have been through a converter carry
    /// the comma SRT uses, and reading it as an unparseable number would drop the cue entirely.
    func testMillisecondsMayBeSeparatedByAComma() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01,250 --> 00:00:02,000
            words
            """)

        XCTAssertEqual(parsed.first?.start, 1.25)
    }

    /// A cue whose timing cannot be read has nowhere to be rendered, so it is dropped rather than
    /// guessed at - and dropping it must not take the rest of the file with it.
    func testACueWithAnUnreadableTimingLineIsDroppedOnItsOwn() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            whenever --> later
            dropped

            00:00:05.000 --> 00:00:06.000
            kept
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 5, text: "kept")])
    }

    // MARK: - Cue text

    func testMarkupIsStrippedFromTheText() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            <v Speaker>the <i>emphasised</i> word<00:00:02.000><c> after</c>
            """)

        XCTAssertEqual(parsed.first?.text, "the emphasised word after")
    }

    /// Escapes are decoded after the markup strip, so a bracket someone wrote as text is never read
    /// as the start of a tag that swallows the rest of the line.
    func testEscapesAreDecodedAfterMarkupIsStripped() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            5 &lt; 6 &amp;&amp; 7 &gt; 6 &quot;yes&quot; it&#39;s
            """)

        XCTAssertEqual(parsed.first?.text, "5 < 6 && 7 > 6 \"yes\" it's")
    }

    /// The ampersand is decoded last for this: someone writing about an escape gets the escape back
    /// rather than the character it names.
    func testAnEscapedEscapeIsDecodedOnlyOnce() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            write &amp;lt; for a bracket
            """)

        XCTAssertEqual(parsed.first?.text, "write &lt; for a bracket")
    }

    // MARK: - Everything that is not cue text

    func testCueIdentifiersAreNotTranscript() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            opening
            00:00:01.000 --> 00:00:02.000
            first

            closing
            00:00:03.000 --> 00:00:04.000
            second
            """)

        XCTAssertEqual(parsed, [
            TranscriptLine(start: 1, text: "first"),
            TranscriptLine(start: 3, text: "second")
        ])
    }

    func testNoteBlocksAreNotTranscript() {
        let parsed = VTTTranscript.parse("""
            WEBVTT
            Kind: captions
            Language: en

            NOTE
            this file was generated by a robot

            00:00:01.000 --> 00:00:02.000
            words
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 1, text: "words")])
    }

    func testWindowsLineEndingsParse() {
        let contents = "WEBVTT\r\n\r\n00:00:01.000 --> 00:00:02.000\r\nwords\r\n"

        XCTAssertEqual(VTTTranscript.parse(contents), [TranscriptLine(start: 1, text: "words")])
    }

    // MARK: - Repetition

    /// Two lines is the window YouTube scrolls today, so the overlap is measured rather than assumed
    /// to be one line - a three line window would otherwise render every line twice.
    func testAWindowTallerThanTwoLinesStillDeduplicates() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            one
            two
            three

            00:00:02.000 --> 00:00:03.000
            two
            three
            four
            """)

        XCTAssertEqual(parsed, [
            TranscriptLine(start: 1, text: "one two three"),
            TranscriptLine(start: 2, text: "four")
        ])
    }

    /// Only the scrolling window is collapsed, not the video's vocabulary. Someone who says the same
    /// word twice a minute apart said it twice.
    func testALineThatRecursLaterIsRenderedAgain() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            yeah

            00:00:02.000 --> 00:00:03.000
            yeah

            00:00:03.000 --> 00:00:04.000
            totally

            00:00:04.000 --> 00:00:05.000
            yeah
            """)

        XCTAssertEqual(parsed, [
            TranscriptLine(start: 1, text: "yeah"),
            TranscriptLine(start: 3, text: "totally"),
            TranscriptLine(start: 4, text: "yeah")
        ])
    }

    // MARK: - Timestamps that are not timestamps

    /// The one that could take a whole run down. The renderer turns every start time into an `Int`,
    /// and `Int(Double.nan)` is a trap rather than a thrown error, so a single bad file part way
    /// through 36,000 folders would kill the export outright rather than cost one cue. `Double`
    /// reads all of these as numbers, which is exactly why the parser cannot.
    func testATimestampThatIsNotANumberDropsOnlyItsOwnCue() {
        let malformed = [
            "00:00:nan", "00:00:inf", "00:00:infinity", "00:00:0x1p10", "00:00:99999999999999999999.000",
            // Not numeric extremes, but they used to read as a time rather than as malformed
            "00:00:", "00::01.000"
        ]

        for stamp in malformed {
            let parsed = VTTTranscript.parse("""
                WEBVTT

                \(stamp) --> 00:00:30.000
                dropped

                00:00:40.000 --> 00:00:41.000
                kept
                """)

            XCTAssertEqual(parsed, [TranscriptLine(start: 40, text: "kept")], "\(stamp) should not have parsed")
        }
    }

    /// `Int("-05")` succeeds, so without a digit check a malformed stamp becomes a negative time and
    /// renders as a `[-5:00]` link pointing at `&t=-300`.
    func testANegativeTimestampIsRejectedRatherThanRendered() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:-05:00.000 --> 00:00:30.000
            dropped

            00:00:40.000 --> 00:00:41.000
            kept
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 40, text: "kept")])
    }

    /// A leading sign used to be swallowed rather than refused, which read a negative stamp as the
    /// positive time it was not.
    func testASignedTimestampIsRejectedRatherThanSilentlyMadePositive() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            -00:00:05.000 --> 00:00:30.000
            dropped
            """)

        XCTAssertEqual(parsed, [])
    }

    func testAPlausibleTimestampStillParses() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            01:59:59.999 --> 02:00:01.000
            near the end of a long one
            """)

        XCTAssertEqual(parsed.first?.start ?? 0, 7199.999, accuracy: 0.001)
    }

    /// The range guard is a backstop for whatever the digit checks let through, not an opinion about
    /// how long a video may be. A day-long livestream still parses.
    func testALivestreamLengthTimestampStillParses() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            30:00:00.000 --> 30:00:01.000
            still going
            """)

        XCTAssertEqual(parsed.first?.start, 108000)
    }

    // MARK: - Caption files nobody generated automatically

    /// Broadcast style captions open each speaker turn with `>>`. Treating every closing bracket as
    /// the end of a tag deleted those, and left a double space where the speaker used to be.
    func testSpeakerMarkersAndStrayBracketsSurvive() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            >> JOHN: 6 > 5 is true
            """)

        XCTAssertEqual(parsed.first?.text, ">> JOHN: 6 > 5 is true")
    }

    /// Pinned rather than endorsed. WebVTT requires a literal `<` be written as an escape, so a raw
    /// one is malformed input, and this is what a browser does with it too. It is here so the
    /// behaviour cannot change silently under a refactor.
    func testARawOpeningBracketSwallowsTheRestOfTheLine() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            5 < 6 and that is that
            """)

        XCTAssertEqual(parsed.first?.text, "5")
    }

    /// Also pinned rather than endorsed. Two identical consecutive cues collapse to one, because the
    /// overlap rule cannot tell a scrolling window from someone saying the same thing twice in a
    /// row. For the auto-generated files this exists to read, collapsing is right far more often.
    func testTwoIdenticalConsecutiveCuesCollapseToOne() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            Go!

            00:00:02.000 --> 00:00:03.000
            Go!
            """)

        XCTAssertEqual(parsed, [TranscriptLine(start: 1, text: "Go!")])
    }

    /// And the other end of the same limit: a window that re-wraps its text instead of repeating a
    /// line verbatim has no line-level overlap to find, so the sentence renders twice. Fixing it
    /// would mean matching partial lines, which risks dropping words somebody said - a worse trade
    /// than the duplication. Pinned so the cost is visible if anyone revisits it.
    func testARewrappedWindowRepeatsItself() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            so I went to the store

            00:00:02.000 --> 00:00:03.000
            so I went to the store and then
            """)

        XCTAssertEqual(parsed.map(\.text), ["so I went to the store", "so I went to the store and then"])
    }

    /// A file whose separator lines carry a space would never close a cue on the empty-line rule
    /// alone, so every cue identifier in it would arrive as words somebody said.
    func testAWhitespaceSeparatorStillClosesACueThatHasPayload() {
        // Written out rather than as a multiline literal, because the separators are single spaces
        // and any editor that trims trailing whitespace would quietly delete the thing under test
        let padded = "WEBVTT\n \n00:00:01.000 --> 00:00:02.000\nfirst\n \ncue-3\n"
            + "00:00:03.000 --> 00:00:04.000\nsecond\n"

        let parsed = VTTTranscript.parse(padded)

        XCTAssertEqual(parsed.map(\.text), ["first", "second"])
    }

    /// The one shape the termination rule gets wrong, pinned rather than fixed. A blank-looking line
    /// between two payload lines closes the cue early and drops what follows it. YouTube cannot
    /// produce this - its padding stands in for a window row that is not there, and an absent row
    /// only ever sits at an edge - and the alternative rule loses the first spoken line of every
    /// auto-generated file, which is a far more common file than this one.
    func testAWhitespaceLineBetweenTwoPayloadLinesEndsTheCueEarly() {
        let parsed = VTTTranscript.parse("WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nfirst\n \nsecond\n")

        XCTAssertEqual(parsed.map(\.text), ["first"])
    }

    // MARK: - More escapes

    func testTheRemainingNamedEscapesDecode() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            it&apos;s a&nbsp;test&lrm;&rlm;
            """)

        XCTAssertEqual(parsed.first?.text, "it's a test\u{200E}\u{200F}")
    }

    /// Not part of WebVTT, but caption files that came through a tool with an HTML step in it are
    /// full of numbered curly quotes, and left alone they render as themselves mid-sentence.
    func testNumberedEscapesDecodeInBothBases() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            it&#8217;s a&#160;test &#x27;ok&#x27;
            """)

        XCTAssertEqual(parsed.first?.text, "it\u{2019}s a test 'ok'")
    }

    /// The reason numbered references are decoded before the ampersand: someone writing about an
    /// escape gets the escape back rather than the character it names.
    func testAnEscapedNumberedEscapeIsDecodedOnlyOnce() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            write &amp;#39; for an apostrophe
            """)

        XCTAssertEqual(parsed.first?.text, "write &#39; for an apostrophe")
    }

    /// Something that merely looks like a reference is left exactly as written rather than eaten.
    func testTextThatIsNotAReferenceIsLeftAlone() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            issue &#42 and &#; and &#xZZ; stay
            """)

        XCTAssertEqual(parsed.first?.text, "issue &#42 and &#; and &#xZZ; stay")
    }

    /// The bug a two pass decoder cannot avoid. `&#38;` and `&#x26;` both name an ampersand, so
    /// decoding numbers before names turns `&#38;lt;` into a bracket nobody wrote - and decoding
    /// names first breaks `&amp;#39;` the same way. Only a pass that never re-reads its own output
    /// gets both right.
    func testAnAmpersandAnEscapeProducedIsNotItselfDecoded() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            &#38;lt; and &#x26;lt; and &amp;lt; and &amp;#39; and &#38;#39;
            """)

        XCTAssertEqual(parsed.first?.text, "&lt; and &lt; and &lt; and &#39; and &#39;")
    }

    /// One character, three spellings, one set of bytes in content.md. Letting the named spelling
    /// give a space and the numbered one give U+00A0 would mean a grep across 36,000 files finds one
    /// and misses the other.
    func testEverySpellingOfANoBreakSpaceGivesTheSameBytes() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            a&nbsp;b&#160;c&#xA0;d
            """)

        XCTAssertEqual(parsed.first?.text, "a b c d")
        XCTAssertEqual(parsed.first?.text.unicodeScalars.map(\.value), [97, 32, 98, 32, 99, 32, 100])
    }

    /// The renderer writes one transcript line per markdown line and only substitutes `\n`, so a
    /// decoded carriage return or line separator would break the structure of content.md from inside
    /// a cue. Every other control character goes with them.
    func testDecodedControlCharactersCannotBreakTheMarkdownLine() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            before&#13;&#10;after&#8232;more&#0;and&#9;done
            """)

        // A break becomes a space and everything else is simply removed, which is why `more` and
        // `and` end up adjacent: nothing invents whitespace that was not there
        XCTAssertEqual(parsed.first?.text, "before after moreand done")
        XCTAssertEqual(parsed.first?.text.contains(where: \.isNewline), false)
    }

    /// A numbered escape can name a C1 control as easily as a C0 one, and U+0085 is a line break
    /// living in that block - so leaving the upper range out would have let a cue break the markdown
    /// after all.
    func testC1ControlsAreFlattenedToo() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            before&#133;after&#144;done
            """)

        XCTAssertEqual(parsed.first?.text, "before afterdone")
        XCTAssertEqual(parsed.first?.text.unicodeScalars.contains { (0x7F...0x9F).contains($0.value) }, false)
    }

    /// `UInt32(_:radix:)` takes a leading sign, so this used to decode to an apostrophe nobody wrote
    /// - the same hole the timestamps had before the digit checks went in.
    func testASignedNumberedEscapeIsNotAnEscape() {
        let parsed = VTTTranscript.parse("""
            WEBVTT

            00:00:01.000 --> 00:00:03.000
            it&#+39;s and it&#-39;s
            """)

        XCTAssertEqual(parsed.first?.text, "it&#+39;s and it&#-39;s")
    }

    // MARK: - Reading from disk

    func testLoadingAFileThatIsNotThereIsNil() {
        let missing = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathComponent("transcript.vtt")

        XCTAssertNil(VTTTranscript.load(from: missing))
    }

    /// The two answers a caller has to tell apart: yt-dlp never wrote a file here, versus yt-dlp
    /// wrote one and there was nothing in it. Only the first is nil.
    func testLoadingAFileWithNoCuesIsEmptyRatherThanNil() throws {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("\(UUID().uuidString).vtt")
        try "WEBVTT\nKind: captions\nLanguage: en\n".write(to: url, atomically: true, encoding: .utf8)
        defer { try? FileManager.default.removeItem(at: url) }

        XCTAssertEqual(VTTTranscript.load(from: url), [])
    }

    /// A yt-dlp write interrupted mid-codepoint used to lose every cue in the file, and then have
    /// the folder describe itself as a video YouTube had answered with silence. The bad bytes are
    /// repaired instead, so nil keeps meaning only "there is no file here".
    func testAFileWithBadBytesKeepsTheCuesThatReadFine() throws {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("\(UUID().uuidString).vtt")
        var bytes = Data("WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nan em dash ".utf8)
        bytes.append(contentsOf: [0xE2, 0x80])  // the first two bytes of an em dash, and then nothing
        try bytes.write(to: url)
        defer { try? FileManager.default.removeItem(at: url) }

        let parsed = try XCTUnwrap(VTTTranscript.load(from: url))

        XCTAssertEqual(parsed.count, 1)
        XCTAssertEqual(parsed.first?.start, 1)
        XCTAssertTrue(parsed.first?.text.hasPrefix("an em dash") == true, "got \(parsed.first?.text ?? "nothing")")
    }

    func testAByteOrderMarkDoesNotHideTheFirstCue() throws {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("\(UUID().uuidString).vtt")
        var bytes = Data([0xEF, 0xBB, 0xBF])
        bytes.append(contentsOf: Data("WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nwords\n".utf8))
        try bytes.write(to: url)
        defer { try? FileManager.default.removeItem(at: url) }

        XCTAssertEqual(VTTTranscript.load(from: url), [TranscriptLine(start: 1, text: "words")])
    }

    // MARK: - Helpers

    private func fixture(named name: String) throws -> String {
        let url = try XCTUnwrap(Bundle.module.url(forResource: name, withExtension: "vtt", subdirectory: "Fixtures"),
                                "missing fixture \(name).vtt")
        return try String(contentsOf: url, encoding: .utf8)
    }
}
